1. Given two 2x2 matrices representing the number of likes and comments on two Instagram posts over two days, write Python code to multiply them and display the resulting matrix.


In [ ]:
import numpy as np

A = np.array([
    [120, 150],
    [180, 200]
])

B = np.array([
    [10, 15],
    [20, 25]
])

result = np.dot(A, B)

print("Likes Matrix (A):")
print(A)

print("\nComments Matrix (B):")
print(B)

print("\nResult of Matrix Multiplication (A × B):")
print(result)

Likes Matrix (A):
[[120 150]
 [180 200]]

Comments Matrix (B):
[[10 15]
 [20 25]]

Result of Matrix Multiplication (A × B):
[[4200 5550]
 [5800 7700]]


2. Create a simple Python function linear_regression_predict(x, m, c) that takes an input value x, slope m, and intercept c, and returns the predicted output y for a linear regression equation y = mx + c.


y=mx+c

where:

1. x = Input value
2. m = Slope
3. c = Intercept
4. y = Predicted output

In [ ]:
def linear_regression_predict(x, m, c):
    y = m * x + c
    return y

x = 10
m = 2.5
c = 5

prediction = linear_regression_predict(x, m, c)

print("Input (x):", x)
print("Slope (m):", m)
print("Intercept (c):", c)
print("Predicted Output (y):", prediction)

Input (x): 10
Slope (m): 2.5
Intercept (c): 5
Predicted Output (y): 30.0


3. Imagine you are predicting the delivery time for Zomato orders based on distance. Given three distances (2km, 5km, 8km) and a linear regression equation y = 4x + 10 (where y is minutes), use your function from the previous task to calculate the predicted delivery time for each distance.


y=4x+10

where:

x = Distance (km)
y = Predicted delivery time (minutes)

In [ ]:
def linear_regression_predict(x, m, c):
    return m * x + c

m = 4
c = 10

distances = [2, 5, 8]

for distance in distances:
    predicted_time = linear_regression_predict(distance, m, c)
    print(f"Distance: {distance} km -> Predicted Delivery Time: {predicted_time} minutes")

Distance: 2 km -> Predicted Delivery Time: 18 minutes
Distance: 5 km -> Predicted Delivery Time: 30 minutes
Distance: 8 km -> Predicted Delivery Time: 42 minutes


4. Explain in your own words what the slope and intercept represent in the context of Flipkart's product price prediction (e.g., predicting price based on product rating). Write 2-3 sentences for each term.


Slope (m)

The slope represents how much the predicted product price changes when the product rating increases by 1 point. If the slope is positive, higher-rated products are expected to have higher prices. If it is negative, higher ratings are associated with lower predicted prices.

Intercept (c)

The intercept is the predicted product price when the product rating is 0. Although a rating of 0 may not be realistic on Flipkart, the intercept serves as the starting value of the linear regression model and helps define the prediction equation.

5. Use ChatGPT to ask: 'How does matrix multiplication help in training a machine learning model like Spotify's song recommendation system?' Summarize the answer in your own words in 3-4 sentences.

Matrix multiplication helps machine learning models process large amounts of user and song data efficiently. In Spotify's recommendation system, it combines user preferences with song features to calculate how likely a user is to enjoy a particular song. During training, matrix multiplication is used repeatedly to make predictions and update the model's parameters. This allows the recommendation system to become more accurate and provide personalized song suggestions over time.