1. Implement a K-Nearest Neighbors (KNN) classifier in Python to predict whether a Flipkart product review is 'positive' or 'negative' using a small dataset of review texts and their labels.<br><br><em><strong>Hint:</strong> Use scikit-learn's KNeighborsClassifier and convert the text data into numerical features using CountVectorizer.</em>


In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = pd.DataFrame({
    "review": [
        "Excellent product",
        "Very bad quality",
        "Loved it",
        "Waste of money",
        "Highly recommended",
        "Not worth buying",
        "Amazing phone",
        "Poor battery life",
        "Best purchase",
        "Terrible experience"
    ],
    "label": [
        "positive", "negative", "positive", "negative",
        "positive", "negative", "positive", "negative",
        "positive", "negative"
    ]
})

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["review"])

y = data["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.3333333333333333


2. Compare the accuracy of KNN using Euclidean distance vs. Manhattan distance on a dataset of Spotify song features (e.g., tempo, danceability, energy) to classify songs as 'workout' or 'chill' playlists.<br><br><em><strong>Hint:</strong> Use the 'metric' parameter in KNeighborsClassifier to switch between 'euclidean' and 'manhattan'.</em>


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

spotify = pd.DataFrame({
    "tempo":[120,110,130,90,150,100,140,95],
    "danceability":[0.8,0.6,0.9,0.4,0.95,0.5,0.88,0.45],
    "energy":[0.9,0.5,0.95,0.3,0.98,0.4,0.92,0.35],
    "playlist":["workout","chill","workout","chill",
                "workout","chill","workout","chill"]
})

X = spotify[["tempo","danceability","energy"]]
y = spotify["playlist"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

knn_e = KNeighborsClassifier(n_neighbors=3, metric="euclidean")
knn_e.fit(X_train, y_train)
pred_e = knn_e.predict(X_test)

knn_m = KNeighborsClassifier(n_neighbors=3, metric="manhattan")
knn_m.fit(X_train, y_train)
pred_m = knn_m.predict(X_test)

print("Euclidean Accuracy:", accuracy_score(y_test, pred_e))
print("Manhattan Accuracy:", accuracy_score(y_test, pred_m))

Euclidean Accuracy: 1.0
Manhattan Accuracy: 1.0


3. Use Gaussian Naive Bayes to classify whether an IRCTC train booking is likely to be 'confirmed' or 'waitlisted' based on features like booking time, train popularity, and travel day (use a small mock dataset).


In [3]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

booking = pd.DataFrame({
    "booking_time":[10,20,15,5,18,12,25,8],
    "popularity":[9,8,7,5,10,6,9,4],
    "travel_day":[1,5,6,2,7,3,6,1],
    "status":[1,0,1,0,1,0,1,0]
})

X = booking[["booking_time","popularity","travel_day"]]
y = booking["status"]

model = GaussianNB()

model.fit(X,y)

prediction = model.predict([[14,8,5]])

print("Prediction:",
      "Confirmed" if prediction[0]==1 else "Waitlisted")

Prediction: Confirmed


c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


4. Build a Multinomial Naive Bayes classifier to categorize WhatsApp chat messages as 'personal', 'group', or 'spam' using example message texts and labels.<br><br><em><strong>Constraint:</strong> Use scikit-learn's MultinomialNB and show the confusion matrix for your results.</em>


In [4]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

messages = pd.DataFrame({
    "text":[
        "See you tonight",
        "Meeting at 5 pm",
        "Congratulations you won prize",
        "Family dinner tomorrow",
        "Project discussion",
        "Click here to earn money",
        "Birthday party",
        "Limited time offer"
    ],
    "label":[
        "personal",
        "group",
        "spam",
        "personal",
        "group",
        "spam",
        "personal",
        "spam"
    ]
})

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(messages["text"])
y = messages["label"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42
)

model = MultinomialNB()

model.fit(X_train,y_train)

pred = model.predict(X_test)

print("Confusion Matrix:\n")
print(confusion_matrix(y_test,pred))

Confusion Matrix:

[[0 1 0]
 [0 0 0]
 [0 1 0]]


5. Use ChatGPT or Copilot to generate Python code for a KNN-based image classifier that distinguishes between images of cricket bats and footballs (use any small sample image dataset or random pixel arrays), then run and test the code, noting any changes you made to get it working.<br><br><em><strong>Hint:</strong> Paste the AI-generated code, describe any errors, and how you fixed them.</em>

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

np.random.seed(42)

bats = np.random.randint(0,100,(20,256))

footballs = np.random.randint(150,255,(20,256))

X = np.vstack((bats, footballs))
y = np.array([0]*20 + [1]*20)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0
