1. Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.

In [1]:
import numpy as np

ratings = np.array([
    [5, 4, 3, 5, 4],
    [4, 5, 4, 3, 5],
    [3, 4, 5, 4, 4],
    [5, 3, 4, 5, 5]  
])

print("All Ratings:")
print(ratings)

All Ratings:
[[5 4 3 5 4]
 [4 5 4 3 5]
 [3 4 5 4 4]
 [5 3 4 5 5]]


In [2]:
selected_ratings = ratings[1:3, :]
print("\nRatings of Second and Third Users:")
print(selected_ratings)


Ratings of Second and Third Users:
[[4 5 4 3 5]
 [3 4 5 4 4]]


2. Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>


In [3]:
import numpy as np

steps = np.array([7500, 8200, 9000, 6700, 10500, 7800, 8500, 9200, 7300, 11000])

print("Daily Steps:")
print(steps)

condition = steps > 8000

print("\nSteps Greater Than 8000 (Boolean Mask):")
print(condition)

high_steps = steps[condition]

print("\nDays with More Than 8000 Steps:")
print(high_steps)

Daily Steps:
[ 7500  8200  9000  6700 10500  7800  8500  9200  7300 11000]

Steps Greater Than 8000 (Boolean Mask):
[False  True  True False  True False  True  True False  True]

Days with More Than 8000 Steps:
[ 8200  9000 10500  8500  9200 11000]


3. Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.


In [4]:
import numpy as np

scores = np.array([180, 195, 210, 175, 220, 190, 205, 185])


print("IPL Match Scores:")
print(scores)

selected_scores = scores[[1, 4, 6]]

print("\nScores from Matches 2, 5, and 7:")
print(selected_scores)

IPL Match Scores:
[180 195 210 175 220 190 205 185]

Scores from Matches 2, 5, and 7:
[195 220 205]


4. Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>


In [5]:
import numpy as np

prices = np.array([999, 1499, 2499, 3999, 5999])

print("Original Prices:")
print(prices)

discounted_prices = prices * 0.90

print("\nPrices After 10% Discount:")
print(discounted_prices)

Original Prices:
[ 999 1499 2499 3999 5999]

Prices After 10% Discount:
[ 899.1 1349.1 2249.1 3599.1 5399.1]


5. Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.

In [6]:
import numpy as np

ratings = np.array([5, -2, 3, 0, -1, 4, -5, 2])

print("Original Ratings:")
print(ratings)

ratings[ratings < 0] = 0

print("\nRatings After Replacing Negative Values with 0:")
print(ratings)

Original Ratings:
[ 5 -2  3  0 -1  4 -5  2]

Ratings After Replacing Negative Values with 0:
[5 0 3 0 0 4 0 2]
