1. Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.


In [1]:
import numpy as np

friend1 = np.array([8000, 9500, 7000, 10000, 12000, 11000, 9000])
friend2 = np.array([7500, 9000, 8000, 9500, 10000, 10500, 8500])


addition = friend1 + friend2
subtraction = friend1 - friend2
multiplication = friend1 * friend2
division = friend1 / friend2

print("Friend 1 Steps:", friend1)
print("Friend 2 Steps:", friend2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Friend 1 Steps: [ 8000  9500  7000 10000 12000 11000  9000]
Friend 2 Steps: [ 7500  9000  8000  9500 10000 10500  8500]

Element-wise Addition:
[15500 18500 15000 19500 22000 21500 17500]

Element-wise Subtraction:
[  500   500 -1000   500  2000   500   500]

Element-wise Multiplication:
[ 60000000  85500000  56000000  95000000 120000000 115500000  76500000]

Element-wise Division:
[1.06666667 1.05555556 0.875      1.05263158 1.2        1.04761905
 1.05882353]


2. Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.


In [2]:
import numpy as np

user_preferences = np.array([
    [5, 3, 1],
    [2, 4, 6],
    [7, 1, 2]
])

song_popularity = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [5, 10, 15]
])

recommendation_dot = np.dot(user_preferences, song_popularity)

recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("Recommendation Matrix using dot():")
print(recommendation_dot)

print("\nRecommendation Matrix using matmul():")
print(recommendation_matmul)

Recommendation Matrix using dot():
[[100 185 270]
 [110 200 290]
 [ 95 185 275]]

Recommendation Matrix using matmul():
[[100 185 270]
 [110 200 290]
 [ 95 185 275]]


3. Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values.


In [3]:
import numpy as np

image = np.array([
    [120, 150, 180, 200],
    [100, 130, 170, 210],
    [90,  140, 160, 220],
    [80,  110, 190, 240]
])

print("Original Image Matrix:")
print(image)

rotated_image = image.T

print("\nTransposed Image Matrix:")
print(rotated_image)

mean_value = np.mean(image)
median_value = np.median(image)
std_value = np.std(image)
var_value = np.var(image)

print("\nMean Pixel Brightness:", mean_value)
print("Median Pixel Brightness:", median_value)
print("Standard Deviation:", std_value)
print("Variance:", var_value)

Original Image Matrix:
[[120 150 180 200]
 [100 130 170 210]
 [ 90 140 160 220]
 [ 80 110 190 240]]

Transposed Image Matrix:
[[120 100  90  80]
 [150 130 140 110]
 [180 170 160 190]
 [200 210 220 240]]

Mean Pixel Brightness: 155.625
Median Pixel Brightness: 155.0
Standard Deviation: 47.16576486181476
Variance: 2224.609375


4. Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>


In [4]:
import numpy as np

ratings = np.array([
    [1, 2, 1],
    [0, 1, 3],
    [2, 1, 1]
])

print("Rating Correlation Matrix:")
print(ratings)

det = np.linalg.det(ratings)
print("\nDeterminant:")
print(det)

if det != 0:
    inverse = np.linalg.inv(ratings)
    print("\nInverse Matrix:")
    print(inverse)
else:
    print("\nMatrix is not invertible. Modify a value and try again.")

eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Rating Correlation Matrix:
[[1 2 1]
 [0 1 3]
 [2 1 1]]

Determinant:
7.999999999999998

Inverse Matrix:
[[-0.25  -0.125  0.625]
 [ 0.75  -0.125 -0.375]
 [-0.25   0.375  0.125]]

Eigenvalues:
[-0.5+1.32287566j -0.5-1.32287566j  4. +0.j        ]

Eigenvectors:
[[-0.2906191 -0.46134351j -0.2906191 +0.46134351j -0.57735027+0.j        ]
 [ 0.69748583+0.j          0.69748583-0.j         -0.57735027+0.j        ]
 [-0.34874292+0.30756234j -0.34874292-0.30756234j -0.57735027+0.j        ]]


5. Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

In [ ]:
import numpy as np

orders = np.array([
    [120, 150, 130, 170, 160, 180],  
    [100, 140, 110, 150, 145, 165]   
])

print("Original Array (2x6):")
print(orders)

reshaped = orders.reshape(3, 4)
print("\nReshaped Array (3x4):")
print(reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array:")
print(flattened)


part1, part2 = np.split(flattened, 2)
print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

stacked = np.vstack((part1, part2))
print("\nVertically Stacked Array:")
print(stacked)

Original Array (2x6):
[[120 150 130 170 160 180]
 [100 140 110 150 145 165]]

Reshaped Array (3x4):
[[120 150 130 170]
 [160 180 100 140]
 [110 150 145 165]]

Flattened Array:
[120 150 130 170 160 180 100 140 110 150 145 165]

Part 1:
[120 150 130 170 160 180]

Part 2:
[100 140 110 150 145 165]

Vertically Stacked Array:
[[120 150 130 170 160 180]
 [100 140 110 150 145 165]]
