1. Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel) and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.


In [1]:

import numpy as np

np.random.seed(42)

image = np.random.randint(0, 10, (5, 5))

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

output_size = 5 - 3 + 1
activation_map = np.zeros((output_size, output_size))

for i in range(output_size):
    for j in range(output_size):
        region = image[i:i+3, j:j+3]
        activation_map[i, j] = np.sum(region * kernel)

print("Input Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nActivation Map:")
print(activation_map)

Input Image:
[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[ -2.  -1.   5.]
 [ -4.  -4.  10.]
 [-12.  -4.   9.]]


2. Implement a Python function apply_stride_convolution(input_matrix, kernel, stride) that performs convolution with a given stride on a 6x6 matrix and a 3x3 kernel, returning the resulting activation map.<br><br><em><strong>Hint:</strong> Use nested loops to move the kernel by the stride value over the input matrix.</em>


In [2]:
import numpy as np

def apply_stride_convolution(input_matrix, kernel, stride):
    input_rows, input_cols = input_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = ((input_rows - kernel_rows) // stride) + 1
    output_cols = ((input_cols - kernel_cols) // stride) + 1

    activation_map = np.zeros((output_rows, output_cols))

    for i in range(0, input_rows - kernel_rows + 1, stride):
        for j in range(0, input_cols - kernel_cols + 1, stride):
            region = input_matrix[i:i + kernel_rows, j:j + kernel_cols]
            value = np.sum(region * kernel)

            out_i = i // stride
            out_j = j // stride
            activation_map[out_i, out_j] = value

    return activation_map

input_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

stride = 2

activation_map = apply_stride_convolution(input_matrix, kernel, stride)

print("Input Matrix:")
print(input_matrix)

print("\nKernel:")
print(kernel)

print("\nActivation Map:")
print(activation_map)

Input Matrix:
[[1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]
 [1 2 3 4 5 6]
 [7 8 9 1 2 3]
 [4 5 6 7 8 9]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[-6.  3.]
 [-6.  3.]]


3. Modify your convolution code to add zero-padding of 1 around the input matrix before applying the convolution, and show the new activation map output.


In [3]:
import numpy as np

def convolution_with_padding(input_matrix, kernel, padding=1):
    padded_matrix = np.pad(
        input_matrix,
        pad_width=padding,
        mode='constant',
        constant_values=0
    )

    input_rows, input_cols = padded_matrix.shape
    kernel_rows, kernel_cols = kernel.shape

    output_rows = input_rows - kernel_rows + 1
    output_cols = input_cols - kernel_cols + 1

    activation_map = np.zeros((output_rows, output_cols))

    for i in range(output_rows):
        for j in range(output_cols):
            region = padded_matrix[i:i+kernel_rows, j:j+kernel_cols]
            activation_map[i, j] = np.sum(region * kernel)

    return padded_matrix, activation_map

input_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9],
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 1, 2, 3],
    [4, 5, 6, 7, 8, 9]
])

kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

padded_matrix, activation_map = convolution_with_padding(
    input_matrix,
    kernel,
    padding=1
)

print("Padded Matrix:")
print(padded_matrix)

print("\nActivation Map:")
print(activation_map)

Padded Matrix:
[[0 0 0 0 0 0 0 0]
 [0 1 2 3 4 5 6 0]
 [0 7 8 9 1 2 3 0]
 [0 4 5 6 7 8 9 0]
 [0 1 2 3 4 5 6 0]
 [0 7 8 9 1 2 3 0]
 [0 4 5 6 7 8 9 0]
 [0 0 0 0 0 0 0 0]]

Activation Map:
[[-10.  -4.   5.   5.  -4.   7.]
 [-15.  -6.   3.   3.  -6.  15.]
 [-15.  -6.   3.   3.  -6.  15.]
 [-15.  -6.   3.   3.  -6.  15.]
 [-15.  -6.   3.   3.  -6.  15.]
 [-13.  -4.   5.   5.  -4.  10.]]


4. Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel or Laplacian kernel for edge detection and an averaging kernel for blur.</em>


In [ ]:
import numpy as np

image = np.array([
    [10, 20, 30, 40, 50],
    [15, 25, 35, 45, 55],
    [20, 30, 40, 50, 60],
    [25, 35, 45, 55, 65],
    [30, 40, 50, 60, 70]
])

edge_kernel = np.array([
    [ 0, -1,  0],
    [-1,  4, -1],
    [ 0, -1,  0]
])

blur_kernel = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
]) / 9.0

def convolve(image, kernel):
    img_h, img_w = image.shape
    k_h, k_w = kernel.shape

    out_h = img_h - k_h + 1
    out_w = img_w - k_w + 1

    output = np.zeros((out_h, out_w))

    for i in range(out_h):
        for j in range(out_w):
            region = image[i:i+k_h, j:j+k_w]
            output[i, j] = np.sum(region * kernel)

    return output

edge_output = convolve(image, edge_kernel)
blur_output = convolve(image, blur_kernel)

print("Edge Detection Output\t\tBlur Output")
print("-" * 50)

for i in range(edge_output.shape[0]):
    left = np.array2string(edge_output[i], precision=2)
    right = np.array2string(blur_output[i], precision=2)
    print(f"{left}\t{right}")

Edge Detection Output		Blur Output
--------------------------------------------------
[0. 0. 0.]	[25. 35. 45.]
[0. 0. 0.]	[30. 40. 50.]
[0. 0. 0.]	[35. 45. 55.]


5. Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice. Show the input and output arrays and briefly describe what feature your filter detects.

In [5]:
input_image = np.array([
    [10, 10, 10, 10, 10, 10, 10, 10],
    [10, 20, 20, 20, 20, 20, 20, 10],
    [10, 20, 50, 50, 50, 50, 20, 10],
    [10, 20, 50, 90, 90, 50, 20, 10],
    [10, 20, 50, 90, 90, 50, 20, 10],
    [10, 20, 50, 50, 50, 50, 20, 10],
    [10, 20, 20, 20, 20, 20, 20, 10],
    [10, 10, 10, 10, 10, 10, 10, 10]
])

In [6]:
kernel = np.array([
    [-1, 0, 1],
    [-1, 0, 1],
    [-1, 0, 1]
])

In [7]:
import numpy as np

def convolve(image, kernel):
    h, w = image.shape
    kh, kw = kernel.shape

    out = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(out.shape[0]):
        for j in range(out.shape[1]):
            region = image[i:i+kh, j:j+kw]
            out[i, j] = np.sum(region * kernel)

    return out